// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("mackerel_otlp")
	ScopeName = "github.com/mackerelio/opentelemetry-collector-mackerel/exporter/mackerelotlpexporter"
)

const (
	TracesStability  = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelDevelopment
)
