package mackerelotlpexporter

import (
	"context"
	"errors"
	"fmt"
	"net"
	"os"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/config/configopaque"
	"go.opentelemetry.io/collector/exporter"
	"go.opentelemetry.io/collector/exporter/otlpexporter"
	"go.opentelemetry.io/collector/exporter/otlphttpexporter"
)

func createMetrics(ctx context.Context, set exporter.Settings, cfg component.Config) (exporter.Metrics, error) {
	mackerelOTLPCfg, ok := cfg.(*Config)
	if !ok {
		return nil, errors.New("cannot reflect to mackerelotlpexporter.Config")
	}
	mackerelApiKey, err := mackerelOTLPCfg.mackerelApiKey()
	if err != nil {
		return nil, err
	}

	factory := otlpexporter.NewFactory()

	otlpSet := exporter.Settings{
		// If "mackerelotlp" type name in settings are passed, the test generated by mdatagen fails.
		ID:                component.NewIDWithName(factory.Type(), set.ID.Name()),
		TelemetrySettings: set.TelemetrySettings,
		BuildInfo:         set.BuildInfo,
	}

	otlpCfg, ok := factory.CreateDefaultConfig().(*otlpexporter.Config)
	if !ok {
		return nil, errors.New("cannot reflect to otlphttpexporter.Config")
	}
	otlpCfg.QueueConfig = mackerelOTLPCfg.QueueConfig
	otlpCfg.RetryConfig = mackerelOTLPCfg.RetryConfig
	otlpCfg.TimeoutConfig = mackerelOTLPCfg.TimeoutConfig
	otlpCfg.ClientConfig.Headers = configopaque.MapList{
		{Name: "Mackerel-Api-Key", Value: mackerelApiKey},
	}
	metricsEndpoint := mackerelOTLPCfg.MetricsEndpoint
	if os.Getenv("OTELCOL_MACKEREL_PREFER_IPV4") != "" {
		resolved, originalHost, err := resolveIPv4(ctx, metricsEndpoint)
		if err != nil {
			return nil, err
		}
		metricsEndpoint = resolved
		if originalHost != "" {
			otlpCfg.ClientConfig.TLS.ServerName = originalHost
		}
	}
	otlpCfg.ClientConfig.Endpoint = metricsEndpoint
	otlpCfg.ClientConfig.Compression = "gzip"
	otlpCfg.ClientConfig.TLS.Insecure = mackerelOTLPCfg.InSecure

	exp, err := factory.CreateMetrics(ctx, otlpSet, otlpCfg)
	if err != nil {
		return nil, err
	}
	return exp, nil
}

func createTraces(ctx context.Context, set exporter.Settings, cfg component.Config) (exporter.Traces, error) {
	mackerelOTLPCfg, ok := cfg.(*Config)
	if !ok {
		return nil, errors.New("cannot reflect to mackerelotlpexporter.Config")
	}
	mackerelApiKey, err := mackerelOTLPCfg.mackerelApiKey()
	if err != nil {
		return nil, err
	}

	factory := otlphttpexporter.NewFactory()

	otlpHTTPSet := exporter.Settings{
		// If "mackerelotlp" type name in settings are passed, the test generated by mdatagen fails.
		ID:                component.NewIDWithName(factory.Type(), set.ID.Name()),
		TelemetrySettings: set.TelemetrySettings,
		BuildInfo:         set.BuildInfo,
	}

	otlpHTTPCfg, ok := factory.CreateDefaultConfig().(*otlphttpexporter.Config)
	if !ok {
		return nil, errors.New("cannot reflect to otlphttpexporter.Config")
	}
	otlpHTTPCfg.QueueConfig = mackerelOTLPCfg.QueueConfig
	otlpHTTPCfg.RetryConfig = mackerelOTLPCfg.RetryConfig
	otlpHTTPCfg.ClientConfig.Timeout = mackerelOTLPCfg.TimeoutConfig.Timeout
	otlpHTTPCfg.ClientConfig.Headers = configopaque.MapList{
		{Name: "Accept", Value: "*/*"},
		{Name: "Mackerel-Api-Key", Value: mackerelApiKey},
	}
	otlpHTTPCfg.ClientConfig.Endpoint = mackerelOTLPCfg.TracesEndpoint
	otlpHTTPCfg.ClientConfig.Compression = "gzip"
	otlpHTTPCfg.ClientConfig.TLS.Insecure = mackerelOTLPCfg.InSecure

	exp, err := factory.CreateTraces(ctx, otlpHTTPSet, otlpHTTPCfg)
	if err != nil {
		return nil, err
	}
	return exp, nil
}

func createLogs(ctx context.Context, set exporter.Settings, cfg component.Config) (exporter.Logs, error) {
	mackerelOTLPCfg, ok := cfg.(*Config)
	if !ok {
		return nil, errors.New("cannot reflect to mackerelotlpexporter.Config")
	}
	mackerelApiKey, err := mackerelOTLPCfg.mackerelApiKey()
	if err != nil {
		return nil, err
	}

	factory := otlphttpexporter.NewFactory()

	otlpHTTPSet := exporter.Settings{
		// If "mackerelotlp" type name in settings are passed, the test generated by mdatagen fails.
		ID:                component.NewIDWithName(factory.Type(), set.ID.Name()),
		TelemetrySettings: set.TelemetrySettings,
		BuildInfo:         set.BuildInfo,
	}

	otlpHTTPCfg, ok := factory.CreateDefaultConfig().(*otlphttpexporter.Config)
	if !ok {
		return nil, errors.New("cannot reflect to otlphttpexporter.Config")
	}
	otlpHTTPCfg.QueueConfig = mackerelOTLPCfg.QueueConfig
	otlpHTTPCfg.RetryConfig = mackerelOTLPCfg.RetryConfig
	otlpHTTPCfg.ClientConfig.Timeout = mackerelOTLPCfg.TimeoutConfig.Timeout
	otlpHTTPCfg.ClientConfig.Headers = configopaque.MapList{
		{Name: "Accept", Value: "*/*"},
		{Name: "Mackerel-Api-Key", Value: mackerelApiKey},
	}
	otlpHTTPCfg.ClientConfig.Endpoint = mackerelOTLPCfg.LogsEndpoint
	otlpHTTPCfg.ClientConfig.Compression = "gzip"
	otlpHTTPCfg.ClientConfig.TLS.Insecure = mackerelOTLPCfg.InSecure

	exp, err := factory.CreateLogs(ctx, otlpHTTPSet, otlpHTTPCfg)
	if err != nil {
		return nil, err
	}
	return exp, nil
}

// resolveIPv4 resolves the host in endpoint to an IPv4 address.
// Returns the resolved endpoint and the original hostname.
// If the host is already an IP address, it returns the endpoint unchanged.
func resolveIPv4(ctx context.Context, endpoint string) (string, string, error) {
	host, port, err := net.SplitHostPort(endpoint)
	if err != nil {
		return endpoint, "", nil
	}
	if net.ParseIP(host) != nil {
		return endpoint, "", nil
	}
	ips, err := net.DefaultResolver.LookupIP(ctx, "ip4", host)
	if err != nil {
		return "", "", fmt.Errorf("resolve %s to IPv4: %w", host, err)
	}
	if len(ips) == 0 {
		return "", "", fmt.Errorf("no IPv4 address found for %s", host)
	}
	return net.JoinHostPort(ips[0].String(), port), host, nil
}