version: 2
project_name: otelcol-mackerel
env:
  - CGO_ENABLED=0
release:
  use_existing_draft: true
builds:
  - id: otelcol-mackerel-linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    dir: _build
    binary: otelcol-mackerel
  - id: otelcol-mackerel-darwin
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
    dir: _build
    binary: otelcol-mackerel
archives:
  - id: otelcol-mackerel
    ids:
      - otelcol-mackerel-linux
      - otelcol-mackerel-darwin
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
nfpms:
  - id: otelcol-mackerel
    ids:
      - otelcol-mackerel-linux
    package_name: otelcol-mackerel
    homepage: https://mackerel.io/
    maintainer: Hatena <mackerel-developers@hatena.ne.jp>
    description: Mackerel OpenTelemetry Collector
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: otelcol-mackerel.service
        dst: /lib/systemd/system/otelcol-mackerel.service
      - src: otelcol-mackerel.conf
        dst: /etc/otelcol-mackerel/otelcol-mackerel.conf
        type: config|noreplace
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
dockers_v2:
  - id: otelcol-mackerel
    ids:
      - otelcol-mackerel-linux
    images:
      - mackerel/otelcol-mackerel
      - ghcr.io/mackerelio/opentelemetry-collector-mackerel/otelcol-mackerel
    tags:
      - "{{.Version}}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: false
# monorepo setting is not available in GoReleaser free edition,
# which means that running goreleaser with including monorepo tags will result in unintended version names.
# The workaround is setting custom tags via `GORELEASER_CURRENT_TAG` and `GORELEASER_PREVIOUS_TAG` environment value.
# cf.) https://goreleaser.com/cookbooks/set-a-custom-git-tag/
# monorepo:
#   tag_prefix: v
