name: CI for pull requests

on:
  pull_request:

jobs:
  test-go:
    strategy:
      matrix:
        go-version: [stable, oldstable, ""]
    uses: ./.github/workflows/wf-test-go.yml
    with:
      go-version: ${{ matrix.go-version }}
