name: test Go library module

on:
  workflow_call:
    inputs:
      go-cache:
        type: boolean
        default: false
      working-directory:
        type: string
        required: true

jobs:
  lint:
    strategy:
      matrix: &test_golib_matrix
        go-version: [stable, oldstable]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: ${{ inputs.go-cache }}
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          args: --timeout=10m
          working-directory: ${{ inputs.working-directory }}

  test:
    strategy:
      matrix: *test_golib_matrix
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: ${{ inputs.go-cache }}
          working-directory: ${{ inputs.working-directory }}
      - name: Run Go tests
        run: |
          set -o pipefail
          go test ./... -cover -json > ./go-test.out
        working-directory: ${{ inputs.working-directory }}
      - name: Format test result
        if: always()
        run: |
          go tool tparse -all -file ./go-test.out
          go tool tparse -all -file ./go-test.out -format markdown >> "$GITHUB_STEP_SUMMARY"
        working-directory: ${{ inputs.working-directory }}
