name: test all Go library modules

on:
  workflow_call:
    inputs:
      go-cache:
        type: boolean
        default: false

jobs:
  lint:
    strategy:
      matrix: &test_all_golibs_matrix
        go-version: [stable, oldstable]
        os: [ubuntu-latest]
        working-directory:
          - exporter/mackerelotlpexporter
          - confmap/provider/zerocfgprovider
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: ${{ inputs.go-cache }}
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          args: --timeout=10m
          working-directory: ${{ matrix.working-directory }}

  test:
    strategy:
      matrix: *test_all_golibs_matrix
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: ${{ inputs.go-cache }}
      - name: Run Go tests
        run: |
          set -o pipefail
          go test ./... -cover -json > ./go-test.out
        working-directory: ${{ matrix.working-directory }}
      - name: Format test result
        if: always()
        run: |
          go tool tparse -all -file ./go-test.out
          go tool tparse -all -file ./go-test.out -format markdown >> "$GITHUB_STEP_SUMMARY"
        working-directory: ${{ matrix.working-directory }}
